### ISSUE TITLE
MM Errors when missing plume-specific variables

### ISSUE THREAD

**Issue by lukecologne** [KSP-RO/RealPlume#54]
OK, got another issue. When there are only fixedScale, localRotation, localPosition, and not the "Plume-specific" variables in a plume, MM throws errors for your new configs. The old configs seem to be fine with only having the "universal" variables. Can confirm the error for Cryogenic_LowerSSME_CE and Hypergolic_UpperWhite, didn't test the rest yet.

**Comment by lukecologne** [comment]
OK, I think I may have found the source of the problem. In the file 000_zRealPlume, missing fields like plumePosition etc. are replaced with the "universal" variables. But since you use new/different names in the plume-specific variables (like corePosition etc.), those are not covered in the patch.

**Comment by lukecologne** [comment]
Tested my theory, and adding your new variable names to the patch fixes the MM errors. But I only added a few variables, and there are probably some more that I didn't find. You would need to add every variable introduced by you to this file.

**Comment by zorg2044** [comment]
Oh I see the error is thrown up when you don't specify the individual parameters for each individual effect? I always specify them individually so I didnt encounter this in RealPlume-Stock. I will add the new variables to the 000_zRealPlume for the next release.

**Comment by lukecologne** [comment]
Yes, exactly. It isn't that big of a deal, since the plume still works with the missing fields, but it's annoying because effects with missing parameters just have the default value and not the localPosition/fixedScale values, and because the MMCache is not being built.

**Comment by zorg2044** [comment]
Yeah it will be good practice to cover these variables. Shouldn’t be too difficult.

 I am also considering adding a global alphaMult and SaturationMult variable (that will default to 1 and therefore no effect if nothing specified) for all the plumes. Similar to the global emissionMult variable for controlling emission, you can then adjust the entire plumes alpha transparency and saturation if desired.

**Comment by zorg2044** [comment]
Fixed in the dev branch now. Not tested yet.

**Comment by lukecologne** [comment]
The file is still missing fumePosition (not fumeScale), and shockScale and shockPosition.

**Comment by zorg2044** [comment]
Thanks a lot again. Missing ones added here https://github.com/KSP-RO/RealPlume/commit/c82a6d066159bf96b7f90721ee2507801735492b
